# $FreeBSD$

PORTNAME=	xf86-video-sis
PORTVERSION=	0.11.0
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org sis display driver

USE_GL=		gl

XORG_CAT=	driver

.include <bsd.port.mk>
